research_task:
  description: >
    Conduct thorough research on {regulatory_state} and Pharmaceutical Benefit Manager (PBM) in that state,
    their position in the sector, and recent industry trends. 
    Focus on news from the last year, as the current year is 2025.

    Take into account any information from prior interactions: {prior_interactions}

    Participants {participants}
    Meeting Context {context}

  expected_output: >
    A comprehensive report on {regulatory_state}'s Pharmaceutical Benefit Manager (PBM) background, their status in the
    sector, and relevant industry insights. Include a list of 10 bullet points
    highlighting the most crucial information for our meeting and a detailed report summarizing key findings about each participant. 
    Make available a list of references in the appendix focusing off governmental (.gov) and (.org) websites.


product_alignment_task:
  description: >
    Analyze the Pharmaceutical Benefit Manager (PBM) current industry trends, challenges, and opportunities
    relevant to the meeting's context. Consider market reports, recent
    developments, and expert opinions to provide a comprehensive overview of the industry landscape.

    Consider any insights from prior interactions - {prior_interactions}

    Participants {participants}
    Meeting Context {context}

  expected_output: >
    An insightful analysis that identifies major trends, potential
    challenges, and strategic opportunities


regulatory_and_legal_task:
  description: >
    Develop a tailored regulatory approach for {regulatory_state} for Pharmaceutical Benefit Manager (PBM). Consider their position in
    the  sector, regulatory_state size, and potential objections. Prepare strategies
    for handling these objections and identify potential upselling or cross-selling
    opportunities. Develop strategic talking points, questions, and discussion angles
    for the meeting based on the research and industry analysis conducted.

    Factor in any insights from {prior_interactions}
    Meeting Context: {context}
    Meeting Objective: {objective}

  expected_output: >
    A comprehensive sales strategy document including approach, objection handling
    techniques, and additional sales opportunities tailored for the meeting with
    from {regulatory_state}.


meeting_preparation_task:
  description: >
    Compile all the Pharmaceutical Benefit Manager (PBM) research findings, Pharmaceutical Benefit Manager (PBM) industry analysis, and strategic
    talking points into a concise, comprehensive briefing document for
    the meeting with {regulatory_state}. Ensure the briefing is easy to digest and equips the meeting
    participants with all necessary information and strategies.

    Meeting Context {context}
    Meeting Objective {objective}
    Incorporate any relevant points from prior interactions {prior_interactions}

  expected_output: >
    A comprehensive briefing document for the meeting with {regulatory_state} that includes sections for meeting participant-only bios,
    industry overview, talking points, and strategic recommendations. The document should be structured in a logical
    and engaging manner to facilitate a productive and insightful meeting.
